### ISSUE TITLE
[REQUEST] Adicionar quarta apresentacao a Wiki.

### ISSUE THREAD

**Issue by MaiconMares** [Interacao-Humano-Computador/2020.1-Zupper#35]

**Comment by ErickGiffoni** [comment]
Por favor façam isso logo, pois fui avaliar o trabalho de vcs e não consegui fazê-lo

**Comment by MaiconMares** [comment]
> Por favor façam isso logo, pois fui avaliar o trabalho de vcs e não consegui fazê-lo

Resolvido @ErickGiffoni

**Comment by ErickGiffoni** [comment]
Show !
