### ISSUE TITLE
[URGENTE] Artefatos faltando na wiki

### ISSUE THREAD

**Issue by ErickGiffoni** [Interacao-Humano-Computador/2020.1-Zupper#37]
## Artefatos desse ponto de controle faltando
- Planejamento da avaliação do storyboard
- Relato da avaliação do storyboard
- Planejamento da avaliação da análise de tarefas
- Relato da avaliação da análise de tarefas
- Apresentação desse ponto de controle

**Pessoal, façam isso o mais rápido possível, pois não consegui avaliar bem o projeto de vocês**

Data da avaliação: 04/11/2020

**Comment by ErickGiffoni** [comment]
@MaiconMares

**Comment by MaiconMares** [comment]
> @MaiconMares

@ErickGiffoni a nossa Wiki se encontra em: https://interacao-humano-computador.github.io/2020.1-Zupper/ , ela pode ser facilmente acessada ao entrar na página inicial do repositório, lá também estão as 4 apresentações. O relato da avaliação do Storyboard não faz parte desse ponto de controle, o que é pedido no Plano de Ensino é o Planejamento do relato dos resultados da avaliação do Storyboard e da Análise de Tarefas. Todos os artefatos requeridos nesse ponto de controle podem ser encontrados no link acima nas opções Storyboard e Avaliação e Análise de Tarefas e Avaliação.

**Comment by ErickGiffoni** [comment]
Ok, beleza !

**Comment by MaiconMares** [comment]
> Ok, beleza !
> Parabéns pelo trabalho, continuem com dedicação e resiliência.

Muito obrigado @ErickGiffoni. Me dê feedback sobre o quê podemos melhorar.
